### ISSUE TITLE
*spinnaker_link devices honor board_address argument only partly

### ISSUE THREAD

**Issue by tophensen** [SpiNNakerManchester/sPyNNakerExternalDevicesPlugin#42] opened 2017-01-27 10:59 UTC
I just checked out your recent work and to my amazement pushbot_spinnaker_link_retina_device.py works out of the box (super awesome! Thanks a ton!) - if our IO-board is connected to the right spinn-link in a setup of 3 SpiNN-5 boards. I would like to use multiple IO-boards on different spinn-links. 

pushbot_spinnaker_link_retina_device has an argument "board_address" which seems to do the right thing, as if I set this to a board IP address whose external spinn-link interface is disabled in the respective FPGA I receive:
> pacman.exceptions.PacmanConfigurationException: No SpiNNaker Link 0 found on board 192.168.2.33.  This would be true if another chip was found connected at this point

Pacman does not emit this error when the board at board_address has an enabled external spinn-link interface, so board_address does something! However, regardless of which board_address I set, the data I receive is always coming from the same IO-board, which is the "master board" (machineName) in slot 0. The same is reflected in the reports: the mapping and routing does not seem to honor board_address - it always uses machineName and places the vertices accordingly, regardless which board_address I set.

**Comment by alan-stokes** [comment] 2017-01-27 11:18
Hi Tophensen,

I'm glad to know my work is appreciated, we don't get enough of these
messages. lol. I'm also glad that the way I tested it still works out of
the box. Its worth noting that there's a Ethernet support as well, but it
feels rather flaky due to the latency issues between commands etc, but you
could possibly use that to get your multiple bots. Or have multiple
spinnaker machines........

That set of branches are unfortunately currently in review, Rowley is doing
modifications on the branches as we speak.

It might be he bust something during his refactors and is in the middle of
fixing it, but ill leave it to him to respond on greater detail (as its
been months since I looked at this stuff, so even thou I built it, my
memory of it all is fogged. Rowley has been reviewing it recently, so is
more up-to-date with it all). The plan is to get them into the master tool
chain soonish, so it might work by then.

I do note that multiple push bots via the same overall spinnaker machine
were not on my scope of testing (we've only got 1 push bot here, and on a
multiple board machine, there's issues about fpga's etc.) so I'm impressed
it gets anywhere to be honest (I likely started work on that, seeing your
use case as possible, but without a ground to test with.......). It might
be that there's issues that I just didn't take into account during the
initial build of this functionality so apologies if that becomes the case.

Anyhow, if we think we fix it by the time it goes to master, and is proved
to be failed, we could revisit it in capocaccia (if ya bring along a set of
PushBots and SpiNNakerLink bits). mmmmmm push bot football via spinnaker
machines?

regards
Alan

**Comment by rowleya** [comment] 2017-01-31 09:33
I just found the bug here - when we are adding the SpiNNaker Links (spinn_machine/machine.py), we seem to use 0, 0 as the chip, ignoring the actual chip coordinates.  I have fixed this in a branch, but there are currently other issues with that branch which I am in the process of fixing.

**Comment by tophensen** [comment] 2017-01-31 09:34
Thanks for the reply, Alan! Your support is much appreciated! 

I found out that part of the issue is in https://github.com/SpiNNakerManchester/SpiNNMachine/blob/master/spinn_machine/machine.py#L341
add_spinnaker_links(self, version_no) ignores the board address. It should instead read 
```
self._spinnaker_links[
                        chip.ip_address, 0] = SpinnakerLinkData(
                            spinnaker_link_id=0, 
                            connected_chip_x=chip.x,
                            connected_chip_y=chip.y,
                            connected_link=4,
                            board_address=chip.ip_address)
```
This lets sPyNNaker set up the route for the command_sender correctly. However, PACMAN disregards the fact that the link is used by the IO-board and is unavailable for normal spike routing. So I guess this link should be disabled or not added in the first place in spinn_machine/router.py

**Comment by tophensen** [comment] 2017-01-31 09:37
Oh! Just saw your comment, Andrew! We have posted at almost the same time. Thanks for fixing this! Are you also trying to fix the routing issue? If not, I can try to find a solution...

**Comment by alan-stokes** [comment] 2017-01-31 10:17
Hi All,

when you say "PACMAN disregards the fact that the link is used by the
IO-board and is unavailable for normal spike routing"

This may be that you misunderstand how the tools handle external devices.
We exhibit the IO board / connection as a extra chip (called a virutal
chip) in the spinnaker machine but with no sdram, cpu, dtcm resources, and
many more cores than a usual chip. This is why the system doesnt work in a
turos, as those links then have a real chip connected down them.

During placement, the external device vertices are then placed on these
virtual chips via placement constraints, and due to the lack of resources,
the other vertices never go on there.

The routing then just behaves as normal, as nothing will be routed to that
virtual chip that isnt meant to. I forward you to the external device
slides for more info.
https://docs.google.com/presentation/d/1fkR5gY71USl6HdtXJzAZyFd1aX97VpZ7AvMLfooMyQM/edit?usp=sharing

regards
Alan

**Comment by rowleya** [comment] 2017-01-31 10:22
Yes, good timing there!

I am not sure that I understand the routing issue.  Here is what I think should happen:
1) The link used by the IO-board should at first be found not to exist when querying the machine.  This seems to validated by the fact that you are allowed to declare the device as being attached to the link.
1) You declare the device to be attached to the link, and so a virtual chip is created on that link.  The x and y coordinates of the chip will be something outside of the actual physical board but will otherwise have no relationship to the chip to which they are connected.
1) The external device is placed on the virtual chip.
1) Routing will route traffic between the device and any population where there is a projection in the network.  This will send spikes to the device if you have a projection that ends at the device or it will route spikes from the device to a population if you have a projection that starts at the device.

If you find that routing sends spikes to the device where there isn't a projection ending in the device, that would indicate a fault.  Alternatively, if spike data is sent over the link expecting to arrive at a chip that is not the virtual chip, that would also be an error.  Is that what you are seeing?

**Comment by tophensen** [comment] 2017-01-31 10:38
Thank you very much for the clarification, A&A! 

Here's what happens: 
I want to route retina spikes via an IO-Board that is connected to chip 4,8 in a 3xSpiNN-5 torus. The routing table on 4,8, though, looks like this:

> cat routing_table_4_8.rpt 
> Router contains 6 entries
> Index Key        Mask       Route      Default [Cores][Links]
> ----- ---------- ---------- ---------- ------- --------------
>     0 0x000007F0 0xFFFFFFFF 0x00000010 False   [] [SW]
>     1 0x000007F1 0xFFFFFFFF 0x00000010 False   [] [SW]
>     2 0x00000000 0xFFFFFFFF 0x00000010 False   [] [SW]
>     3 0x00000002 0xFFFFFFFF 0x00000010 False   [] [SW]
>     4 0xFEFF0000 0xFFFFC000 0x00000010 False   [] [SW]
>     5 0x00000001 0xFFFFFFFF 0x00000010 False   [] [SW]

So this acts like a sink to the IO-board, which is connected SW of 4,8: Commands from command sender arrive at the board, but retina events (0xFEFF*) are reflected to the board. What happens is, I think, that PACMAN wants to pass them to chip 3,7 which is connected SW:

> cat routing_table_3_7.rpt 
> Router contains 1 entries
> Index Key        Mask       Route      Default [Cores][Links]
> ----- ---------- ---------- ---------- ------- --------------
>     0 0xFEFF0000 0xFFFFC000 0x00000010 True    [] [SW]
> 

That's what I meant with PACMAN is ignoring the fact that link 4 of chip 4,8 is now a spinnaker_link.

**Comment by rowleya** [comment] 2017-01-31 11:25
OK, I have had a look, and I think I understand what the issue is.  When you disable the FPGA link to the SpiNNaker link, you are only disabling the link from 4, 8 (link 4) to 3, 7.  The link from 3, 7 (link 1) to 4, 8 still exists.  I am guessing that the issue then is that the routing algorithm is looking at the route backwards i.e. it can see a way from 3, 7 to 4, 8 and so assumes the opposite is also true!

I have verified this with a "virtual 3-board toroid" locally.  When I disable both the links 4, 8, link 4 and 3, 7,  link 1, the routes are computed correctly.  If I disable only 4, 8, link 4 in the torroid, it produces the same table as you show above.

The routing algorithm we are using is currently using different data structures.  It is possible that something is lost in the translation between the data structures, which causes the issue.  I will investigate.

**Comment by rowleya** [comment] 2017-01-31 11:42
The issue turned out to be that we weren't doing the translation correctly - the virtual chips and links were being left in the down-stream data structures which confused the algorithm.  I have now removed these in a branch, and it seems to produce the correct results.  You should be able to take advantage of this in the PACMAN "fix_virtual_routing" branch.  Let me know if you have any more issues.

**Comment by alan-stokes** [comment] 2017-01-31 12:12
Hi all,

Luis (who seems to be having odd mail issues) states that just disabling
one direction of the bi-directional links has the potential risk of
damaging the FPGA, the robot, or spinnaker. He says you HAVE to disable
both directions of the link 4 of chip 4,8 to avoid potentially damaging
stuff.

parroted from Alan.

**Comment by rowleya** [comment] 2017-01-31 13:01
Yes, I hadn't' thought of this issue!  The FPGA will be attempting to send things to link 4 of 4,8 from 3,7 and so it could end up overloading the board or the robot.  This is particularly true since the robot is sending retina packets down this same link.

One thought for the tools would be to fall over if a SpiNNaker Link is connected in this way, in an attempt to reduce the chances of the overload.  If a BMP is also specified, it could also turn off the board as a protection measure.

**Comment by tophensen** [comment] 2017-01-31 13:44
Thank you, Andrew! Unfortunately the fix_virtual_routing branch does not change things at all. The routing table on chip (4,8) still assigns link 4 (SW) to both packets types.

**Comment by rowleya** [comment] 2017-01-31 13:59
Hmm, there must be something different about the virtual and real machines at that point that I don't understand.  In any case, Luis has requested that you also disable the link coming from 3, 7 (should be link 1) on the other board in the torus.  Do you know how to do this, or do you need help?

**Comment by tophensen** [comment] 2017-01-31 13:59
I followed Steve Temple's instructions to disable one of the links in FPGA 1 on the SpiNN-5 board that carries the SpiNN-IO:

> bmpc> xreg 0 0x40014 0xffffffff 0 0x40018 0 \
>        1 0x40014 0xfffffffc 1 0x40018 0x30 \
>        2 0x40014 0xffffffff 2 0x40018 0

I did not disable the respective link on the other end of the SATA-cable, though. Do you know the right xreg command?

**Comment by rowleya** [comment] 2017-01-31 14:16
From Steve Temple:

Hi,

Luis and I believe that the "xreg" command you have issued is correct (provided
it was sent to the correct Spin5 board...).

There is no need to disable the "corresponding" (3,7) link. The only connections
affected by the need to access the 34-way link connector are between the (4,8)
chip and its FPGA.

Hope this helps...

Steve

**Comment by rowleya** [comment] 2017-01-31 14:17
In that case, can you send me the script you are using and I can have a go on my virtual board and see if it does something similar?  It might be something extra that you have that I don't...

**Comment by tophensen** [comment] 2017-01-31 14:19
Thank you, Andrew and Luis! This is good news!

Andrew, I just found out that in my case (PushBotRetinaDevice) none of the chips pacman/utilities/rig_converters.py traverses is actually .virtual 
Could this be the difference between the virtual board and the real one? I'll send you the script via Email.

**Comment by tophensen** [comment] 2017-01-31 14:22
Now I realize I can attach the script (retina_example.py) right here. It doesn't really do anything fancy...
[retina_example.zip](https://github.com/SpiNNakerManchester/sPyNNakerExternalDevicesPlugin/files/742158/retina_example.zip)

**Comment by rowleya** [comment] 2017-01-31 15:14
That script seems to be a bit old - it seems to use the Ethernet device and have a number of parameters that I don't think are supported any more.  Do you have a more up-to-date script, or is this what has been working for you?

**Comment by tophensen** [comment] 2017-01-31 15:27
This is what worked for me, yes. I have used Ethernet to stream out the IF_curr_exp relayed retina spikes again, but this was commented out already. Here's an even more stripped version that still works: 
```
import spynnaker.pyNN as p
import spynnaker_external_devices_plugin.pyNN as q
from spynnaker_external_devices_plugin.pyNN.external_devices_models.pushbot_spinnaker_link_retina_device import *
import retina_lib as retina_lib

# Setup
p.setup(timestep=1.0)
dim=128

# The retina, connected via spinnaker link
retina_pop = p.Population(
     dim*dim, q.PushBotRetinaDevice, {
      "fixed_key": 0xFEFF0000,
      "polarity": PushBotRetinaResolution.Native128,
      "resolution": PushBotRetinaPolarity.Down,
      "spinnaker_link_id": 0,
      "board_address": "192.168.2.33"      
      },
     label='External retina')

# dummy population the retina can feed into
population = p.Population(dim*dim, p.IF_curr_exp, {}, label='pop_1')
p.Projection(retina_pop, population, #p.OneToOneConnector(10.0,1))
             p.FromListConnector(retina_lib.subSamplerConnector2D(
                 128, dim, 40.0, 1.0)))
        
population.record()
p.run(10000)

print population.getSpikes()
```

**Comment by tophensen** [comment] 2017-02-01 09:00
Here's a new datapoint:
I could make the network map alright and work by setting chip 3,7 as down_core in .spynnaker.cfg
PACMAN picked that info up and routed retina traffic W instead of SW from 4,8

The following down_links line, however, had no effect on the routing, so at some point this information seems to be ignored.
down_links = [(3,7):(4,8):1][(4,8):(3,7):4]

**Comment by rowleya** [comment] 2017-02-01 09:30
The down_links was indeed ignored in the code for real machines (it was used on virtual machines only for some reason).  I have now updated the code, though this is again in a branch.  I am looking at the other details of the system just now, and should have a working updated version soon.  Note that there might be some renaming of components to ensure there is no confusion between Ethernet and SpiNNaker Link connected versions.

**Comment by tophensen** [comment] 2017-02-01 09:52
Alright! Thank you very much again, Andrew!

**Comment by rowleya** [comment] 2017-08-15 15:13
I believe this to be all done and merged.  Please reopen if this still doesn't work.

**Closed by rowleya** 2017-08-15 15:13 UTC
